# Generated by Django 5.2.12 on 2026-04-01 18:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160, verbose_name='título')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('short_description', models.CharField(max_length=220, verbose_name='descrição curta')),
                ('description', models.TextField(verbose_name='descrição completa')),
                ('cover_image', models.ImageField(blank=True, upload_to='recipes/covers/', verbose_name='imagem de capa')),
                ('pdf_file', models.FileField(blank=True, upload_to='recipes/pdfs/', verbose_name='PDF da receita')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='valor')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='destacar na home')),
            ],
            options={
                'verbose_name': 'receita',
                'verbose_name_plural': 'receitas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(default='Prof. Sol Tricô & Crochê', max_length=120, verbose_name='nome da marca')),
                ('teacher_name', models.CharField(default='Professora Sol', max_length=120, verbose_name='nome da professora')),
                ('hero_title', models.CharField(default='Tricô e crochê com afeto, técnica e peças encantadoras.', max_length=160, verbose_name='título principal')),
                ('hero_subtitle', models.TextField(default='Espaço para apresentar a professora, a proposta da marca e o estilo das aulas, receitas e projetos em fios.', verbose_name='subtítulo')),
                ('about_title', models.CharField(default='Um ateliê para aprender e criar', max_length=120, verbose_name='título sobre')),
                ('about_text', models.TextField(default='Aqui entra a biografia da professora, sua experiência com tricô e crochê, método de ensino e a proposta do ateliê.', verbose_name='texto sobre')),
                ('highlight_text', models.CharField(default='Modelos delicados, explicações cuidadosas e receitas pensadas para quem ama fios.', max_length=200, verbose_name='frase de destaque')),
                ('hero_image', models.ImageField(blank=True, upload_to='site/hero/', verbose_name='foto principal')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail de contato')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('whatsapp_number', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp')),
            ],
            options={
                'verbose_name': 'conteúdo do site',
                'verbose_name_plural': 'conteúdo do site',
            },
        ),
        migrations.CreateModel(
            name='VideoTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='tema')),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'tema de vídeo',
                'verbose_name_plural': 'temas de vídeo',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('pending', 'Pendente'), ('paid', 'Pago'), ('failed', 'Falhou'), ('canceled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='status')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='total')),
                ('external_reference', models.CharField(default=uuid.uuid4, editable=False, max_length=40, unique=True, verbose_name='referência externa')),
                ('checkout_url', models.URLField(blank=True, verbose_name='link de checkout')),
                ('mercadopago_preference_id', models.CharField(blank=True, max_length=80, verbose_name='preference id')),
                ('mercadopago_payment_id', models.CharField(blank=True, max_length=80, verbose_name='payment id')),
                ('provider_payload', models.JSONField(blank=True, default=dict, verbose_name='payload do gateway')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='pago em')),
                ('receipt_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='e-mail enviado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='atelier.recipe')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('youtube_id', models.CharField(max_length=30, unique=True, verbose_name='ID do YouTube')),
                ('youtube_url', models.URLField(verbose_name='URL do vídeo')),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='thumbnail')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publicado em')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='importado em')),
                ('is_published', models.BooleanField(default=True, verbose_name='publicado no site')),
                ('is_featured', models.BooleanField(default=False, verbose_name='destacar na home')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='atelier.videotheme', verbose_name='tema')),
            ],
            options={
                'verbose_name': 'vídeo',
                'verbose_name_plural': 'vídeos',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
